#include <iostream>
using namespace std;

// Class with no explicity defined constructors
class A {
public:
};

int main() {
  
  	// Creating object
    A a;
    return 0;
}

/*
Note:

A default constructor is automatically generated by the 
compiler if the programmer does not define one. This 
constructor doesn't take any argument as it is parameter 
less and initializes object members using default values. 
It is also called a zero-argument constructor. However, the 
default constructor is not generated by the compiler if the 
programmer has explicitly defined a constructor.

*/